import { AppConfig } from "@/types/apps";

export const APPS: AppConfig[] = [
  {
    id: "finder",
    name: "Finder",
    icon: "/finder.png",
    description: "File browser",
    accentColor: "#007AFF",
    defaultPosition: { x: 80, y: 40 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 600, height: 400 },
    menuBarTitle: "Finder",
  },
  {
    id: "notes",
    name: "Notes",
    icon: "/notes.png",
    description: "Personal notes and thoughts",
    accentColor: "#FFCC00",
    defaultPosition: { x: 100, y: 50 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 600, height: 400 },
    menuBarTitle: "Notes",
  },
  {
    id: "messages",
    name: "Messages",
    icon: "/messages.png",
    description: "Chat with AI personas",
    accentColor: "#34C759",
    defaultPosition: { x: 150, y: 80 },
    defaultSize: { width: 800, height: 550 },
    minSize: { width: 500, height: 400 },
    menuBarTitle: "Messages",
  },
  {
    id: "photos",
    name: "Photos",
    icon: "/photos.png",
    description: "Photo library",
    accentColor: "#FF6B6B",
    defaultPosition: { x: 130, y: 60 },
    defaultSize: { width: 900, height: 650 },
    minSize: { width: 600, height: 450 },
    menuBarTitle: "Photos",
  },
  {
    id: "music",
    name: "Music",
    icon: "/music.png",
    description: "Music library",
    accentColor: "#FA2D48",
    defaultPosition: { x: 140, y: 70 },
    defaultSize: { width: 900, height: 650 },
    minSize: { width: 600, height: 450 },
    menuBarTitle: "Music",
  },
  {
    id: "calendar",
    name: "Calendar",
    icon: "/calendar.png",
    description: "Calendar and events",
    accentColor: "#FF3B30",
    defaultPosition: { x: 170, y: 60 },
    defaultSize: { width: 900, height: 700 },
    minSize: { width: 700, height: 500 },
    menuBarTitle: "Calendar",
  },
  {
    id: "iterm",
    name: "iTerm",
    icon: "/iterm.png",
    description: "Terminal emulator",
    accentColor: "#00D455",
    defaultPosition: { x: 120, y: 70 },
    defaultSize: { width: 800, height: 500 },
    minSize: { width: 500, height: 300 },
    menuBarTitle: "iTerm",
  },
  {
    id: "settings",
    name: "Settings",
    icon: "/settings.png",
    description: "System preferences",
    accentColor: "#8E8E93",
    defaultPosition: { x: 200, y: 100 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 700, height: 400 },
    menuBarTitle: "System Settings",
  },
  {
    id: "textedit",
    name: "TextEdit",
    icon: "/textedit.png",
    description: "Plain text editor",
    accentColor: "#8E8E93",
    defaultPosition: { x: 160, y: 90 },
    defaultSize: { width: 700, height: 500 },
    minSize: { width: 400, height: 300 },
    menuBarTitle: "TextEdit",
    showOnDockByDefault: false,
    multiWindow: true,
    cascadeOffset: 30,
  },
  {
    id: "preview",
    name: "Preview",
    icon: "/preview.png",
    description: "Image and PDF viewer",
    accentColor: "#007AFF",
    defaultPosition: { x: 180, y: 100 },
    defaultSize: { width: 800, height: 600 },
    minSize: { width: 400, height: 300 },
    menuBarTitle: "Preview",
    showOnDockByDefault: false,
    multiWindow: true,
    cascadeOffset: 30,
  },
];

export function getAppById(id: string): AppConfig | undefined {
  return APPS.find((app) => app.id === id);
}

export function getAppIds(): string[] {
  return APPS.map((app) => app.id);
}
